### ISSUE TITLE
Sentence tokenizer

### ISSUE THREAD

**Issue by Henry-E** [tdozat/Parser-v3#3]
Hey,

In the conllu results the Stanford sentence tokenizer / segmentation score top for all the English corpuses, in some cases by a big margin. http://universaldependencies.org/conll18/results-sentences.html

Are you able to share the sentence tokenizer? Or recommend what you think is the best sentence tokenizer publicly available for English.

Thanks very much for any help you're able to provide!

**Comment by Henry-E** [comment]
In another issue someone mentioned a decent sentence tokenizer available with the CoreNLP client from Stanford https://github.com/stanfordnlp/stanfordnlp/issues/50

**Comment by qipeng** [comment]
@Henry-E Actually the [stanfordnlp repo](https://github.com/stanfordnlp/stanfordnlp/) contains code to run the sentence tokenizer we used for the Shared Task. We also provide trained models that can be downloaded right within Python. Hope this helps!
