### ISSUE TITLE
Suggestions about how to realize BERT fine-tuning

### ISSUE THREAD

**Issue by longxudou** [tdozat/Parser-v3#7]
Hi, I want to modify Parser-v3 for BERT fine-tuning version using TF-Hub modules. Is there any suggestion about how to realize this?  I have finished this in PyTorch using AllenNLP, while the TF version is a bit difficult.

**Comment by longxudou** [comment]
We have realized a bert-parser based on Parser-V3. Please visit this [link](https://github.com/WangYuxuan93/Parser-v3/tree/bert).

**Comment by jbrry** [comment]
Hi @DreamerDeo, is the AllenNLP version available to view online?

**Comment by longxudou** [comment]
Hi, @Jbar-ry 

You could use our system for CoNLL2019 shared task, including DM,PSD,UCCA,AMR,EDS.  [link](https://github.com/DreamerDeo/HIT-SCIR-CoNLL2019)
Based on the input format(conllu or sdp), you should modify the dataset reader.

**Comment by jbrry** [comment]
Thank you @DreamerDeo for the helpful resource!
